---
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  builder: html
  fail_on_warning: false
  configuration: documentation/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
