---
version: 2
sphinx:
  builder: html
  fail_on_warning: false
  configuration: documentation/source/conf.py
formats: []
python:
  version: 3.8
  install:
    - method: pip
      path: .
    - requirements: documentation/requirements.txt
  system_packages: false
